###
GET http://localhost:80/xaml/0.0.1 HTTP/1.1

### 注册
POST http://localhost:80/users/register HTTP/1.1
content-type: application/json

{
    "name": "bcmray1",
    "email": "bcmray@qq.com",
    "password":"114514"
}

### 登录
POST http://localhost:80/users/login HTTP/1.1
content-type: application/json

{
    "account":"bcmray1",
    "password":"114514"
}

### 获取信息
POST http://localhost:80/users/online HTTP/1.1
content-type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Mn0.RNeFDX7SxiSNOPNx5b43BuahR8UMZgzYbLRjmOfmGak"
}

### 更改头像
POST http://localhost:80/users/upload_avatar HTTP/1.1
content-type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.EhhwoXjWshFm3fYkMbOL8VQPcxjj9wQ9W-igdaq71U0",
    "avatar":"1"
}

### 白名单
POST http://localhost:80/whitelist/request HTTP/1.1
content-type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.EhhwoXjWshFm3fYkMbOL8VQPcxjj9wQ9W-igdaq71U0",
    "nickname":"bcmray",
    "does":"我也不知道来干啥"
}

### 获取列表
POST http://localhost:80/whitelist/list HTTP/1.1
content-type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.EhhwoXjWshFm3fYkMbOL8VQPcxjj9wQ9W-igdaq71U0"
}

###  更改白名单
POST http://localhost:80/whitelist/change HTTP/1.1
content-type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.EhhwoXjWshFm3fYkMbOL8VQPcxjj9wQ9W-igdaq71U0",
    "id":1,
    "status":1
}

### (mc)查找白名单
GET http://localhost:80/mcserver/whitelist/bcmray HTTP/1.1

###
POST http://localhost:80/sm/t HTTP/1.1
content-type: application/json

{ 
    "stroke_color":"#8cb4ff",
    "current_station":"abc",
    "next_station":"ef",
    "current_line":"8", 
    "change_line":"3",
    "change_line_color":"#d22"
}

###
GET http://localhost:80/sm

### 获取权限列表
GET http://localhost:80/admin/permissions/list HTTP/1.1

### 获取原权限列表
GET http://localhost:80/admin/permissions/rawlist HTTP/1.1